### ISSUE TITLE
fix_attach

### ISSUE THREAD

**Issue by neludina** [fl0w3rs/saprp#3]
**Ваш запрос функции связан с проблемой? Пожалуйста, опишите.**
Да. связан с проблемой. Проблема заключается в том, что на сервере присутствует система аттачей, но, она является не рабочей. Не рабочая она в плане того,что во-первых,не возможно сохранить аттач, во-вторых, он не синхронизируется, то-есть,Человек одевает у себя его на экране, правильно выставляет, но у других людей на экране он сидит криво, или вообще не на месте.
**Опишите решение, которое вы хотели бы видеть**
Что бы исправили данную систему, или заменили на более лучшую.

**Опишите альтернативы, которые вы рассматривали**
Отсутствует. 

**Дополнительный контекст**
Отсутствуют.

**Comment by fl0w3rs** [comment]
я подумаю
