### ISSUE TITLE
 system_for_doctors_and_firefighters

### ISSUE THREAD

**Issue by neludina** [fl0w3rs/saprp#4]
**Ваш запрос функции связан с проблемой? Пожалуйста, опишите.**
Да,связан с проблемой того,что у пожарных очень маленький функционал. Мы отыгрываем через /doic,через команды спинальный щит,каталки, и все объекты,которые юзаем. Но, это выглядит очень не красиво и хотелось бы сделать такую вещь...

**Опишите решение, которое вы хотели бы видеть**
Добавить систему,допустим команду /medic, после ввода которой, у пользователя вылазит панель,где он может выбрать каталку. нажимая на каталку, у него появляется еще 3 строки,для выбора,что ли, не знаю,если честно как это называется, первая допустим, прикрепить каталку к игроку, вторая, это поставить каталку рядом с пользователем, третья, удалить каталку. Что делает первая строка? Появляется каталка, которая прикреплена к персонажу, спереди, мол он ее катит. Вторая строка,выполняет функцию размещения каталки уже как обьекта на земле. Что бы у нее появилась типо колисия,на нее можно было лець игроку, и так далее(такая система есть на гамбите, ее оттуда можно вырезать,по идеи), третья,собственно удаляет каталку. Дальше, в панели есть вторая типо, опять же,строка, с надписью спинальный щит, и там еще 2 строки, типо удалить спинальный щит, и разместить(функции теже что и для каталки,короче,кроме прикрепить). Да, я взнаю,этот текст очень сложно переварить, но я не шарю в павно, и не могу сказать,как эта штука называется,вот честно.

**Опишите альтернативы, которые вы рассматривали**
Добавить систему маппинга на сервере, так мы сами сможем поставить ту же самую каталку. и так далее. 

**Дополнительный контекст**
Отсутствует.

**Comment by fl0w3rs** [comment]
делаю

**Comment by b3r4** [comment]
зактнись

**Comment by fl0w3rs** [comment]
сук
