### ISSUE TITLE
Обнова

### ISSUE THREAD

**Issue by fl0w3rs** [fl0w3rs/saprp#5]
- [x] 1. /hood - возможность открывать капот;
**Теперь можно и /hood и /bonnet**
- [x] 2. /helpanims - помощь по анимкам да и в целом навигация по команда не помешала бы (даже я администратор не знаю всех команд);
**/anims || /animlist || /animations || /animhelp**
- [x] 3. /editplate - возможность редактировать текущие номерные знаки (там только создать и удалить);
**Теперь чтобы изменить просто ещё раз /setplate || /setsign**
- [ ] 4. Сделать текстдравы для сигнала 100, кнопки паники и игровой зоны и синхронизировать их с базой;
- [ ] 5. /breaks - возможность добавлять ограждение (типо выставлять обьекты такие как конусы с возможностью их редактирования);
- [ ] 6. /bls (выдается обьект сумки)
- [x] 7. /window [1-4] (возможность открываиь окна, мелочь но приятно)
- [x] 8. /whitelist;
**Будет сделано через сайт**
- [ ] 9. Улучшить /goscar (в плане что бы администрация могла изменять данный список, динамичность кароче);
**Редактирование будет сделано через сайт**
- [ ] 10. /tp (такая-же система как с /goscar. Администрация сможет создавать список телепортов)
**Редактирование будет сделано через сайт**
- [ ] 11. /fire, /stopfire (название говорит само за себя);
- [ ] 12. /apanel (Админская панель, в ней можно запретить команды, попасть в белый список);
- [ ] 13. интерьеры, их я скину тебе чуть позже.
- [x] 14. Сделать два уровня админки, т.е:
1 - отдел приёма кандидатов;
2 - администрация
- [ ] 15. Сделать команду по типу /gpsb (gps по № блоку, желательно что бы администрация их так-де могла редактировать)
- [ ] 16. Обычная система /gps (будет полезна поскольку множество игроков не знают карты)
- [x] 17. Когда выбираешь точку на карте (еск > карта) что бы весвечивалось диалоговое окно с выборос метка или тп (тп-шит когда на левую клавишу жмеш)
- [x] 18. /blocktp что бы запретить тп к себе;
- [ ] 19. система ника (можно задать личный ник по типу у игрока в клиенте ник 12345, но на сервере у него будет ник Yaroslav D.);
- [ ] 20. система званий (можно будет задать звание игроку, будет прописыватся после ника)

**Comment by fl0w3rs** [comment]
> пизда нахуй

э

**Comment by b3r4** [comment]
ха
